import './globals.css'
import { Michroma } from 'next/font/google'
import BootstrapJs from './bootstrapJs'

const os = Michroma({ weight: "400", subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={os.className}>
        <BootstrapJs />
        {children}
      </body>
    </html>
  )
}
